<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        if(DB::table('products')->count() == 0){
            $products = [
                [
                    'name' => 'Urea Fertilizer 50kg',
                    'category_id' => 1,
                    'hsn_code' => '3102',
                    'unit_id' => 5,
                    'gst_id' => 2,
                    'mrp' => 280,
                    'price' => 260,
                    'opening_stock' => 100,
                    'is_active' => 1,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'DAP Fertilizer 50kg',
                    'category_id' => 1,
                    'hsn_code' => '3105',
                    'unit_id' => 5,
                    'gst_id' => 2,
                    'mrp' => 1350,
                    'price' => 1300,
                    'opening_stock' => 50,
                    'is_active' => 1,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'Wheat Seeds HD-2967',
                    'category_id' => 3,
                    'hsn_code' => '1209',
                    'unit_id' => 1,
                    'gst_id' => 1,
                    'mrp' => 120,
                    'price' => 110,
                    'opening_stock' => 200,
                    'is_active' => 1,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'Rice Seeds Hybrid',
                    'category_id' => 3,
                    'hsn_code' => '1209',
                    'unit_id' => 1,
                    'gst_id' => 1,
                    'mrp' => 150,
                    'price' => 140,
                    'opening_stock' => 180,
                    'is_active' => 1,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'Maize Seeds Premium',
                    'category_id' => 3,
                    'hsn_code' => '1209',
                    'unit_id' => 1,
                    'gst_id' => 1,
                    'mrp' => 200,
                    'price' => 190,
                    'opening_stock' => 120,
                    'is_active' => 1,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'Glyphosate Herbicide 1L',
                    'category_id' => 2,
                    'hsn_code' => '3808',
                    'unit_id' => 3,
                    'gst_id' => 4,
                    'mrp' => 450,
                    'price' => 420,
                    'opening_stock' => 80,
                    'is_active' => 1,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'Chlorpyrifos Insecticide 1L',
                    'category_id' => 2,
                    'hsn_code' => '3808',
                    'unit_id' => 3,
                    'gst_id' => 4,
                    'mrp' => 520,
                    'price' => 500,
                    'opening_stock' => 60,
                    'is_active' => 1,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'Neem Oil Organic 1L',
                    'category_id' => 4,
                    'hsn_code' => '3808',
                    'unit_id' => 3,
                    'gst_id' => 1,
                    'mrp' => 300,
                    'price' => 280,
                    'opening_stock' => 70,
                    'is_active' => 1,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'Micronutrient Fertilizer Mix',
                    'category_id' => 1,
                    'hsn_code' => '3105',
                    'unit_id' => 6,
                    'gst_id' => 3,
                    'mrp' => 600,
                    'price' => 580,
                    'opening_stock' => 90,
                    'is_active' => 1,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'Tomato Seeds Hybrid',
                    'category_id' => 3,
                    'hsn_code' => '1209',
                    'unit_id' => 6,
                    'gst_id' => 1,
                    'mrp' => 50,
                    'price' => 45,
                    'opening_stock' => 300,
                    'is_active' => 1,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'Onion Seeds',
                    'category_id' => 3,
                    'hsn_code' => '1209',
                    'unit_id' => 6,
                    'gst_id' => 1,
                    'mrp' => 40,
                    'price' => 35,
                    'opening_stock' => 250,
                    'is_active' => 1,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'Potash Fertilizer',
                    'category_id' => 1,
                    'hsn_code' => '3104',
                    'unit_id' => 5,
                    'gst_id' => 2,
                    'mrp' => 900,
                    'price' => 850,
                    'opening_stock' => 60,
                    'is_active' => 1,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'Plant Growth Regulator',
                    'category_id' => 2,
                    'hsn_code' => '3808',
                    'unit_id' => 4,
                    'gst_id' => 4,
                    'mrp' => 350,
                    'price' => 320,
                    'opening_stock' => 40,
                    'is_active' => 1,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'Sprayer Pump Manual 16L',
                    'category_id' => 2,
                    'hsn_code' => '8424',
                    'unit_id' => 7,
                    'gst_id' => 5,
                    'mrp' => 1200,
                    'price' => 1100,
                    'opening_stock' => 30,
                    'is_active' => 1,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'Bio Fertilizer Culture',
                    'category_id' => 4,
                    'hsn_code' => '3101',
                    'unit_id' => 2,
                    'gst_id' => 1,
                    'mrp' => 250,
                    'price' => 230,
                    'opening_stock' => 100,
                    'is_active' => 1,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'Groundnut Seeds',
                    'category_id' => 3,
                    'hsn_code' => '1202',
                    'unit_id' => 1,
                    'gst_id' => 1,
                    'mrp' => 180,
                    'price' => 170,
                    'opening_stock' => 140,
                    'is_active' => 1,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'Fungicide Mancozeb',
                    'category_id' => 2,
                    'hsn_code' => '3808',
                    'unit_id' => 2,
                    'gst_id' => 4,
                    'mrp' => 400,
                    'price' => 380,
                    'opening_stock' => 75,
                    'is_active' => 1,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'Hybrid Cabbage Seeds',
                    'category_id' => 3,
                    'hsn_code' => '1209',
                    'unit_id' => 6,
                    'gst_id' => 1,
                    'mrp' => 70,
                    'price' => 65,
                    'opening_stock' => 220,
                    'is_active' => 1,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'Drip Irrigation Pipe 16mm',
                    'category_id' => 5,
                    'hsn_code' => '3917',
                    'unit_id' => 3,
                    'gst_id' => 5,
                    'mrp' => 500,
                    'price' => 480,
                    'opening_stock' => 90,
                    'is_active' => 1,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'Organic Compost Bag 50kg',
                    'category_id' => 4,
                    'hsn_code' => '3101',
                    'unit_id' => 5,
                    'gst_id' => 1,
                    'mrp' => 200,
                    'price' => 180,
                    'opening_stock' => 150,
                    'is_active' => 1,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
            ];

            DB::table('products')->insert($products);
        } 
    }
}
